name: Create Release

on:
  workflow_run:
    workflows: 
      - build-linux.yml
      - build-android.yml
    types:
      - completed

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run read-yaml action
        id: yaml
        uses: jbutcher5/read-yaml@main
        with:
          file: './pubspec.yaml'
          key-path: '["version"]'
      - name: Get artifacts
        uses: actions/download-artifact@v4
        with:
          path: /tmp/artifacts
          merge-multiple: true
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: /tmp/artifacts/*
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ steps.yaml.outputs.data }}
          skipIfReleaseExists: true
